### PR TITLE
Fix: pause autoplay when document visibility is lost

### LINKED ISSUE #16: setTimeout causing the gallery to speed up when user leaves the tab.
The setTimeout on the `onHasChanged` callback is causing the gallery to speed up to where it `should` be when a user navigates away from the tab. The solution is to add a check using the visibility api below. Flagging this as an issue for now as I don't have the time to put a fix in place. 

https://github.com/wethegit/wtc-gallery-component/blob/master/src/wtc-gallery-component.js#L487

https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

@marlonmarcello @andrewrubin @liamegan @ShaiaBak - just so you're aware ^

### PR DESCRIPTION
**Pull request by andrewrubin**
Fixes #16 

## Short version
Autoplay galleries now stop when the page is not visible (i.e. you go to another tab).

## Long version
- This runs a check against [`document.visibilityState`](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState), and stops the autoplay timer after its most recent call.
- A listener is then added to the document, which restarts the autoplay timer once the document is visible again. That listener is subsequently removed.

## Demo
The video below shows this in action, using a local `npm link` of this update:
- gallery auto-advances through slides 3 and 4.
- navigate to another tab; slide 5's timer finishes, and pauses on the start of slide 6.
- nothing happens until you navigate back to the tab, at which point autoplay resumes at slide 6.

https://user-images.githubusercontent.com/30575213/153071153-23b6b1a8-1698-44bd-8a13-3a8588002a66.mp4

### CODE REVIEW

File: src/wtc-gallery-component.js [hunk 1]
```diff
@@ -321,6 +321,38 @@ class Gallery extends ElementController {
...
+  /**
+   * Fires when the document's visbility chnages from the "hidden" state;
+   * Resumes autoplay functionality if applicable.
+   */
+  handleVisibilityChange() {
+    if (!this.options.autoplay || document.visibilityState === "hidden") return;
+
+    document.removeEventListener(
+      "visibilitychange",
+      this.handleVisibilityChange.bind(this)
```
Comment (liamegan) [inline src/wtc-gallery-component.js]: Are you sure this works? I had thought that removeEventListener only worked if you supplied it with the exact function that you supplied to the addEventListener. Technically this is a different function as bing acts as a wrapper around the original function. I could be wrong and, if so, please point it out, but this is why I bind all my listeners in the constructor.

**Review by liamegan — CHANGES_REQUESTED** [review]

File: src/wtc-gallery-component.js (hunk 1 above)
Comment (andrewrubin) [reply src/wtc-gallery-component.js]: great shout. We should bind it in the constructor

**Review by liamegan — APPROVED** [review]

File: src/wtc-gallery-component.js (hunk 1 above)
Comment (andrewrubin) [reply src/wtc-gallery-component.js]: Fixed! @liamegan

**Review by liamegan — APPROVED** [review]
